[package]
name = "rumwebs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = "0.11"
log = "0.4.14"
simplelog = "^0.10.0"

rumwebs-http = { path = "./HTTP", version = "0.1.0" }