[server]
ip = "127.0.0.1"
http_port = 7878
tls_port = 443
tls_enabled = false
# Whether HTTP request should be redirected or not.
redirect_http = true
tls_cert_fullchain = ""
tls_cert_privkey = ""
default_host = "localhost"

[application]
thread_count = 8